ProjectLicenses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    # path('snippets/', include('snippets.urls', namespace='snippets')),
    # path('auth/', include('authapp.urls', namespace='auth')),

    path('admin/', admin.site.urls,),

]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path
from mainapp.views import LicenseView

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='main'),
    path('create/', mainapp.bulk_creation_view, name='create'),
    path('update/', mainapp.update, name='update'),
    path('api/license/', LicenseView.as_view(), name='api'),
]

mainapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class License(models.Model):
    """
    TODO:
    В админке сделать
    Пользователь хочет видеть следующие статистические сводки:
    – Общее количество лицензий
    – Количество активированных лицензий
    – Количество неактивированных лицензий
    – Количество просроченных лицензий
    – Гистограмму распределения длительности лицензий
    """
    idlicense = models.AutoField(db_column='idLICENSE', primary_key=True)  # Field name made lowercase.
    code = models.CharField(db_column='CODE', unique=True, max_length=10, blank=True,
                            null=True)  # Field name made lowercase.
    activated = models.DateTimeField(db_column='ACTIVATED', blank=True, null=True)  # Field name made lowercase.
    duration = models.IntegerField(db_column='DURATION', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        result = f'{self.code} {self.duration}'
        return result

    class Meta:
        db_table = 'LICENSE'

mainapp/forms.py
import django.forms as forms


class LicenseCreationForm(forms.Form):
    qty = forms.IntegerField(label='qty')
    dur = forms.IntegerField(label='duration')

    def __str__(self):
        print(self.dur)

class Snippet(forms.Form):
    body = forms.CharField(label='input licences',
                           widget=forms.Textarea())

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from mainapp.models import License
from mainapp.my_func import generator, raspars
from mainapp.forms import LicenseCreationForm, Snippet
from django.contrib import messages

from rest_framework.views import APIView
from .serializers import GetLicenseSerializer, PostLicenseSerializer

from rest_framework.response import Response

# Create your views here.

def index(request):
    context = {'page_title': 'Index page',}
    return render(request, 'mainapp/index.html', context)

def bulk_creation_view(request):
    if request.method == 'POST':
        form = LicenseCreationForm(request.POST or None)
        if form.is_valid():
            qty = int(form['qty'].value())
            dur = int(form['dur'].value())
            # existed = License.objects.all()
            to_input = generator(qty, dur)
            for key, value in to_input.items():
                insert = License(code=key, duration=value)
                insert.save()
            messages.success(request, f'{qty} Licences duration {dur} days added.')
            data = License.objects.all().order_by('-idlicense')[:qty]

            context = {
                'data': to_input,
                'dur': dur,
            }
            return render(request, 'mainapp/succes.html', context)
    else:
        form = LicenseCreationForm()
    context = {
        'form': form
    }

    return render(request, 'mainapp/license_create.html', context)


def update(request):
    if request.method == 'POST':
        form = Snippet(request.POST or None)
        if form.is_valid():
            data = form['body'].value()
            data = raspars(data)
            for key in data.keys():
                obj = get_object_or_404(License, code=key)
            for key, value in data.items():
                change = License.objects.get(code=key)
                now = change.duration
                change.duration = int(now) + int(value)
                change.save()
            messages.success(request, f'{len(data)} Licences was updated.')
            form = Snippet(request.POST or None)
            context = {
                'form': form,
                'data': data,
            }
        return render(request, 'mainapp/succes.html', context)
    else:
            form = Snippet()
    context = {
        'form': form,
    }
    return render(request, 'mainapp/license_update.html', context)


class LicenseView(APIView):
    def get(self, request):
        licences = License.objects.all()
        serializer = GetLicenseSerializer(licences, many=True)
        return Response({"License": serializer.data})

    def post(self, request):
        license = request.data.get('license')
        # Create a License from the above data
        serializer = PostLicenseSerializer(data=license, many=False) #забраем данные
        if serializer.is_valid(raise_exception=True):
            license_saved = serializer.save()
            resp_license = License.objects.get(code=license_saved.code) #получаем сохраненные данные для обратного вывода
            serializer = GetLicenseSerializer(resp_license, many=False) #выводим даннные обратно
        return Response(serializer.data)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project</title>
</head>
<body>

{% block links %}
    <a href="{% url 'admin:index' %}">Admin panel</a>
    <br>
    <br>
    <a href="{% url 'main:create' %}">Create</a>
    <br>
    <br>
    <a href="{% url 'main:update' %}">Update</a>
    <br>
    <br>
    <a href="{% url 'main:api' %}">API</a>


{% endblock links %}

{% block container %}
    {# container content #}
{% endblock container %}

</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

mainapp/templates/mainapp/licence_create.html
{% block container %}
    {% if request.user.is_staff %}
    <form method="POST"> {% csrf_token %}
    {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
    {% endif %}
{% endblock container %}

mainapp/templates/mainapp/license_create.html
{% extends 'mainapp/base.html' %}

{% block container %}
    {% if request.user.is_staff %}
    <form method="POST"> {% csrf_token %}
        <br>
        <br>
    {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
        {% else %}
        <a href="{% url 'admin:index' %}">Admin panel</a>
    {% endif %}
{% endblock container %}

mainapp/templates/mainapp/license_result.html
{% extends 'mainapp/license_create.html' %}

mainapp/templates/mainapp/license_update.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <br>
    <br>
    <p>You may increase or decrease duration.</p>
    <p>Just put in the frame License and days qty after space</p>
    <p>"ABCDE54321 2" for increase</p>
    <p>OR</p>
    <p>"ABCDE54321 -6" for decrease</p>
    {% if request.user.is_staff %}
    <form method="POST"> {% csrf_token %}
        <br>
        {{ form.as_p }}

        <input type="submit" value="Update" />
    </form>
    {% else %}
        <a href="{% url 'admin:index' %}">Admin panel</a>
    {% endif %}


{% endblock container %}

mainapp/templates/mainapp/succes.html
{% extends 'mainapp/base.html' %}

{% block container %}
<h1>Succes</h1>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}"></div>
        {{ message }}
    {% endfor %}
{% endif %}
{% if data %}
    <ul style="list-style-type:none;">
        {% for key, value in data.items %}
            <li>{{key}}</li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock container %}